export const CAR_LIST_REQUEST = 'CAR_LIST_REQUEST'
export const CAR_LIST_SUCCESS = 'CAR_LIST_SUCCESS'
export const CAR_LIST_FAIL = 'CAR_LIST_FAIL'

export const CAR_DETAILS_REQUEST = 'CAR_DETAILS_REQUEST'
export const CAR_DETAILS_SUCCESS = 'CAR_DETAILS_SUCCESS'
export const CAR_DETAILS_FAIL = 'CAR_DETAILS_FAIL'

export const COMPANY_LIST_REQUEST = 'COMPANY_LIST_REQUEST'
export const COMPANY_LIST_SUCCESS = 'COMPANY_LIST_SUCCESS'
export const COMPANY_LIST_FAIL = 'COMPANY_LIST_FAIL'

export const COMPANY_DETAILS_REQUEST = 'COMPANY_DETAILS_REQUEST'
export const COMPANY_DETAILS_SUCCESS = 'COMPANY_DETAILS_SUCCESS'
export const COMPANY_DETAILS_FAIL = 'COMPANY_DETAILS_FAIL'

export const CUSTOMER_LIST_REQUEST = 'CUSTOMER_LIST_REQUEST'
export const CUSTOMER_LIST_SUCCESS = 'CUSTOMER_LIST_SUCCESS'
export const CUSTOMER_LIST_FAIL = 'CUSTOMER_LIST_FAIL'

export const CUSTOMER_DETAILS_REQUEST = 'CUSTOMER_DETAILS_REQUEST'
export const CUSTOMER_DETAILS_SUCCESS = 'CUSTOMER_DETAILS_SUCCESS'
export const CUSTOMER_DETAILS_FAIL = 'CUSTOMER_DETAILS_FAIL'

export const EMPLOYEE_LIST_REQUEST = 'EMPLOYEE_LIST_REQUEST'
export const EMPLOYEE_LIST_SUCCESS = 'EMPLOYEE_LIST_SUCCESS'
export const EMPLOYEE_LIST_FAIL = 'EMPLOYEE_LIST_FAIL'

export const EMPLOYEE_DETAILS_REQUEST = 'EMPLOYEE_DETAILS_REQUEST'
export const EMPLOYEE_DETAILS_SUCCESS = 'EMPLOYEE_DETAILS_SUCCESS'
export const EMPLOYEE_DETAILS_FAIL = 'EMPLOYEE_DETAILS_FAIL'